name: petrichor
description: A weather application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0-dev.3
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  photo_repository:
    path: packages/photo_repository
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env


